In [5]:
#Import & Load
import pandas as pd
import numpy as np

df = pd.read_csv('/4) house Prediction Data Set.csv')
print(df.shape)
df.head()

(505, 1)

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [4]:
#Explore the data
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 1 columns):
 #   Column                                                                                            Non-Null Count  Dtype
---  ------                                                                                            --------------  -----
 0    0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00  505 non-null    object
dtypes: object(1)
memory usage: 4.1+ KB

       0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
count                                                 505
unique                                                505
top      0.04741   0.00  11.930  0  0.5730  6.0300  80...
freq                                                    1

In [6]:
#Check missing values
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing: {df.isnull().sum().sum()}")

Missing values per column:
0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00    0
dtype: int64

Total missing: 0

In [7]:
#Handle missing values
# For numerical columns → fill with median
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)

# For categorical columns → fill with mode
for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Missing values after handling:", df.isnull().sum().sum())

Missing values after handling: 0

/tmp/ipykernel_4289/554905852.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [8]:
#Remove duplicates
print(f"Duplicates before: {df.duplicated().sum()}")
df.drop_duplicates(inplace=True)
print(f"Duplicates after: {df.duplicated().sum()}")

Duplicates before: 0
Duplicates after: 0

In [9]:
#Standardize formats
# Strip whitespace from column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Check dtypes
print(df.dtypes)

0.00632__18.00___2.310__0__0.5380__6.5750__65.20__4.0900___1__296.0__15.30_396.90___4.98__24.00    object
dtype: object

In [10]:
#Save cleaned file
df.to_csv('house_cleaned.csv', index=False)
print("Cleaned dataset saved!")
df.shape

Cleaned dataset saved!

(505, 1)